2018-05-19 10:29:43,006 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:43]
2018-05-19 11:41:59,033 INFO: Microblog startup [in /home/ucleabuntu/microblog/app/__init__.py:43]
2018-05-19 12:27:02,628 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:43]
2018-05-19 12:27:36,094 ERROR: Exception on /edit_profile [POST] [in /home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ubuntu/microblog/app/routes.py", line 83, in edit_profile
    if form.validate_on_submit():
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/ubuntu/microblog/app/forms.py", line 41, in validate_username
    if user is not None:
UnboundLocalError: local variable 'user' referenced before assignment
2018-05-19 12:27:56,198 ERROR: Exception on /edit_profile [POST] [in /home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ubuntu/microblog/app/routes.py", line 83, in edit_profile
    if form.validate_on_submit():
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/ubuntu/microblog/app/forms.py", line 41, in validate_username
    if user is not None:
UnboundLocalError: local variable 'user' referenced before assignment
2018-05-20 07:53:22,664 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:43]
2018-06-09 13:55:58,460 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:43]
2018-06-09 13:56:22,898 ERROR: Exception on /edit_profile [POST] [in /home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ubuntu/microblog/app/routes.py", line 83, in edit_profile
    if form.validate_on_submit():
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 204, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/ubuntu/microblog/venv/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 224, in _run_validation_chain
    validator(form, self)
  File "/home/ubuntu/microblog/app/forms.py", line 41, in validate_username
    if user is not None:
UnboundLocalError: local variable 'user' referenced before assignment
2018-06-09 15:18:08,795 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:43]
2018-06-10 15:54:07,717 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:43]
2018-06-17 12:14:10,327 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:43]
2018-06-17 12:14:29,913 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:43]
2018-06-17 12:15:42,289 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:43]
2018-06-18 16:49:00,748 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:43]
2018-07-17 08:17:23,294 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:43]
